name: Automated AI-SEO Blog

on:
  schedule:
    # Placeholder – real cron is synced by update-workflow.mjs
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: ai-seo-blog
  cancel-in-progress: false

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    env:
      NEWS_FEEDS_GENERAL: ${{ vars.NEWS_FEEDS_GENERAL }}
      NEWS_FEEDS_QUERY: ${{ vars.NEWS_FEEDS_QUERY }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Sync workflow cron from config
        run: node scripts/update-workflow.mjs

      - name: Generate posts
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: npm run generate

      - name: Build site
        run: npm run build
        env:
          ELEVENTY_PATH_PREFIX: /blog/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          publish_branch: main
