name: Automated AI-SEO Blog

on:
  schedule:
    - cron: "0 13 * * *"
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: ai-seo-blog
  cancel-in-progress: false

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    env:
      NEWS_FEEDS_GENERAL: ${{ vars.NEWS_FEEDS_GENERAL }}
      NEWS_FEEDS_QUERY: ${{ vars.NEWS_FEEDS_QUERY }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Generate posts
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: npm run generate

      - name: Commit changes
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add -A
            FIRST_POST=$(git diff --cached --name-only | grep '^src/posts/' | head -n 1)
            if [[ -n "$FIRST_POST" ]]; then
              SLUG=$(basename "$(dirname "$FIRST_POST")")
            else
              SLUG=$(date -u +"%H%M%S")
            fi
            git commit -m "chore(auto): add post $(date -u +"%Y-%m-%d")-$SLUG"
          fi

      - name: Build site
        run: npm run build

      - name: Configure GitHub Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: _site

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
